# Generated by Django 4.2.13 on 2024-05-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoArea', models.CharField(max_length=10, unique=True, verbose_name='Codigo Area')),
                ('nombreArea', models.CharField(max_length=30, unique=True, verbose_name='Nombre Area')),
            ],
        ),
    ]
