# Generated by Django 5.0.4 on 2024-05-26 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('area', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoDep', models.CharField(max_length=10, unique=True, verbose_name='Codigo Departamento')),
                ('nombreDep', models.CharField(max_length=30, unique=True, verbose_name='Nombre Departamento')),
                ('estadoDep', models.BooleanField(default=True, verbose_name='Estado')),
                ('areaDep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='area.area')),
            ],
        ),
    ]
